FROM python:3.11-slim

# Instalar dependencias que necesita Playwright en Linux
RUN apt-get update && apt-get install -y \
    wget gnupg ca-certificates libglib2.0-0 libnss3 libatk1.0-0 libatk-bridge2.0-0 \
    libdrm2 libxkbcommon0 libgbm1 libxcomposite1 libxdamage1 libxfixes3 \
    libxrandr2 libasound2 libatspi2.0-0 libx11-6 libx11-xcb1 libxcb1 \
    libxext6 libxshmfence1 xvfb fonts-liberation libgtk-3-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copiar tu proyecto dentro del contenedor
COPY . /app

# Instalar dependencias Python + navegadores de Playwright
RUN pip install --upgrade pip && \
    pip install scrapy scrapy-playwright playwright && \
    python -m playwright install --with-deps

# Comando por defecto (puedes sobrescribirlo en docker run)
CMD ["scrapy", "crawl", "soriana", "-O", "soriana_precios.jsonl", "-s", "LOG_LEVEL=INFO"]